image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

build_script:
  - echo %APPVEYOR_PROJECT_ID%
  - echo %APPVEYOR_PROJECT_NAME%
  - echo %APPVEYOR_PROJECT_SLUG%
  - echo %APPVEYOR_BUILD_ID%
  - echo %APPVEYOR_BUILD_NUMBER%
  - echo %APPVEYOR_BUILD_VERSION%
  - echo %AAPPVEYOR_JOB_ID%
  - echo %cd%
  - md build
  - cd build
  - cmake -G "Visual Studio 14 Win64" ..
  - MSBuild Millecoin.sln /p:Configuration=Release /m
  - cd src/Release
  - 7z a %APPVEYOR_PROJECT_SLUG%-%APPVEYOR_BUILD_ID%-windows.zip "*.exe"

artifacts:
  - path: build\src\Release\Millecoind.exe
    name: Millecoind.exe
  - path: build\src\Release\service.exe
    name: service.exe
  - path: build\src\Release\zedwallet.exe
    name: zedwallet.exe
  - path: build\src\Release\miner.exe
    name: miner.exe
  - path: build\src\Release\testing*.zip
    name: testing-windows-v$(appveyor_build_version)

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL

deploy:
  tag: v$(appveyor_build_version)
  release: testing-windows-v$(appveyor_build_version)
  description: 'Automated AppVeyor Release v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: HT/ew3LRA9maLoCZHjZYTykRaRVzNU8aSB4Z7EGlnJIydYrngA8gsZMd03WyxXln
  # artifact: build\src\Release\testing-$(appveyor_project_slug)-$(appveyor_build_id).zip
  artifact: 'Millecoind.exe, service.exe, zedwallet.exe, miner.exe, testing-windows-v$(appveyor_build_version)'
  draft: true 
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: false # deploy on tag push only