image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - echo %APPVEYOR_PROJECT_ID%
  - echo %APPVEYOR_PROJECT_NAME%
  - echo %APPVEYOR_PROJECT_SLUG%
  - echo %APPVEYOR_BUILD_ID%
  - echo %APPVEYOR_BUILD_NUMBER%
  - echo %APPVEYOR_BUILD_VERSION%
  - echo %AAPPVEYOR_JOB_ID%
  - echo %cd%
  - md build
  - cd build
  - cmake -G "Visual Studio 14 Win64" ..
  - MSBuild Millecoin.sln /p:Configuration=Release /m
  - 7z a %APPVEYOR_PROJECT_SLUG%-%APPVEYOR_BUILD_ID%.zip build\src\Release\*.exe

artifacts:
  - path: build\src\Release\Millecoind.exe
  - path: build\src\Release\service.exe
  - path: build\src\Release\zedwallet.exe
  - path: build\src\Release\miner.exe
  - path: %APPVEYOR_PROJECT_SLUG%-%APPVEYOR_BUILD_ID%.zip