image: Visual Studio 2015

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-14

build_script:
  - echo $PWD
  - pwd
  - ls
  - echo $(ls -alth)
  - echo "$APPVEYOR_PROJECT_SLUG"
  - echo "$APPVEYOR_PROJECT_NAME"
  - echo "$APPVEYOR_BUILD_FOLDER"
  - echo "$APPVEYOR_BUILD_ID"
  - echo "$APPVEYOR_BUILD_NUMBER"
  - echo "$APPVEYOR_BUILD_VERSION"
  - md build
  - cd build
  - cmake -G "Visual Studio 14 Win64" ..
  - MSBuild Millecoin.sln /p:Configuration=Release /m

artifacts:
  - path: build/src\Release\Millecoind
  - path: build/src\Release\service
  - path: build/src\Release\zedwallet
  - path: build/src\Release\miner